# user nginx;

worker_processes auto;

events {
    use epoll;
    worker_connections 51200;
    multi_accept on;
}

http {
    default_type application/octet-stream;
    sendfile on;
    client_max_body_size 100m; 

    keepalive_timeout  120;

    gzip  on;

    include /php-msf/nginx/conf/conf.d/*.conf;
}