[program:nginx]
command=/php-msf/nginx/sbin/nginx -g "daemon off;"
user=nginx
autostart=true
directory=/php-msf/nginx
stdout_logfile=/php-msf/data/nginx/logs/access.log
stderr_logfile=/php-msf/data/nginx/logs/error.log
