[program:php-fpm]
command=/php-msf/php/sbin/php-fpm -F
user=nginx
group=www-data
autostart=true
autorestart=true
startretries=3
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/php-msf/data/supervisor/logs/php-fpm.log
stderr_logfile=/php-msf/data/supervisor/logs/php-fpm-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
priority=5