[program:php-fpm]
command=/php-msf/php/sbin/php-fpm -F
user=super
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/php-msf/data/php/logs/access.log
stderr_logfile=/php-msf/data/php/logs/error.log